
# Υλοποιήσεις μέσω HashTable: ADTMap
#
# UsingHashTable_ADTMap_test_OBJS	= ADTMap_test.o $(MODULES)/UsingHashTable/ADTMap.o $(MODULES)/UsingHashTable/ADTSet.o

# ADTGraph
#
UsingAdjacencyMap_ADTGraph_test_OBJS = ADTGraph_test.o $(MODULES)/UsingAdjacencyMap/ADTGraph.o $(MODULES)/UsingHashTable/ADTMap.o $(MODULES)/UsingHashTable/ADTSet.o $(MODULES)/UsingLinkedList/ADTList.o

# Ο βασικός κορμός του Makefile
include common.mk